[Hirogin]
#------------------------------------------------
HidukeColNo = 1
MoneyCol = [3,4,5]
ColumnName = ["No","日付","預金番号1","預金番号2","摘要","出金","入金","残高"]

[Momiji]
#------------------------------------------------
HidukeColNo = 2
MoneyCol = [6,7,8]
ColumnName = ["No","日付","預金番号1","預金番号2","摘要","出金","入金","残高"]


[HiroginSouzoku]
#------------------------------------------------
HidukeColNo = 1
MoneyCol = [6,7,8]
ChangeTextCol = [4,9]
ColumnName = ["日付","No","無題","摘要","種類","出金","入金","残高","摘要2"]
ChangeText = [
    "トヨタファイナンス(カブ",
    "ヒロシマギンコウDC",
    "オリコ",
    "ハートフォードセイメイホケ",
    "カゴメ",
    "イトウハム",
    "トウシンブンパイキン",
    "トウシンコウニュウ",
    "UC(アオヤマキャピタル)",
    "クレジット",
    "キュウヨ",
    "フリコミ",
    "リソク",
    "ハイトウキン",
    "フリカエ",
    "テイキ"
    ]