[Hirogin]
#------------------------------------------------
Yokojiku = 5000
Tatejiku = 90
RabelSpace = 2500
etaxYokojiku = 5000
etaxTatejiku = 10
etaxRabelSpace = 500
Rabel = "::"
DougyouTatejiku = 90
ColCount = 5
1Col = 8
2Col = 8
3Col = 15
4Col = 15
5Col = 16
HidukeColNo = 1
MoneyCol = [3,4,5]