[MASTER]
#------------------------------------------------
    ListNameList = [
    "MJS法人税",
    "MJS法人税2",
    "MJS法人税3",
    "MJS法人税4",
    "MJS所得税",
    "MJS所得税2",
    "MJS所得税3",
    "MJS所得税4",
    "MJS所得税5",
    "MJS所得税6",
    "MJS所得税7",
    "MJS所得税8",
    "MJS所得税9",
    "MJS所得税10",
    "MJS所得税11",
    "MJS所得税12",
    "MJS所得税13",
    "MJS所得税14",
    "MJS所得税15",
    "MJS所得税16",
    "MJS所得税17",
    "MJS所得税18",
    "MJS所得税19",
    "MJS所得税20",
    "MJS消費税",
    "MJS消費税2",
    "MJS消費税3",
    "MJSイメージ",
    "etax所得税",
    "etax所得税2",
    "etax消費税",
    "eltax法人税",
    "eltax法人税2",
    "eltax法人税3",
    "eltax法人税4",
    "eltax法人税5",
    "eltax法人税6",
    "エラーリスト"
    ]
#------------------------------------------------
[AIOCR]
#------------------------------------------------
    MJS法人税 = [
    "URL",
    "ページ",
    "法人事業税所得金額総額", 
    "法人県民税(均等割)申告納付税額",
    "利用者ID",
    "コード", 
    "氏名又は名称",
    "発行元名", 
    "発行元所属名",
    "発行元電話番号",
    "発信日時",
    "表示期限",
    "受付日時",
    "受付番号",
    "取扱日",
    "手統名",
    "提出先",
    "年度·期別",
    "納税者氏名",
    "ファイル名称"
    ]

    MJS法人税2 = [    
    "URL",
    "ページ",
    "法人事業税所得金額総額",
    "法人事業税申告納付税額",
    "特別法人事業税申告納付税額",
    "法人県民税(法人税制)課税標準総額",
    "法人県民税(法人税制)申告納付税額",
    "法人県民税(均等割)申告納付税額",
    "利用者ID",
    "コード",
    "氏名又は名称",
    "発行元名",
    "発行元所属名",
    "発行元電話番号",
    "张信日時",
    "表示期限",
    "受付日時",
    "受付番号",
    "取报日",
    "手統名",
    "提出先",
    "年度·期別",
    "納税者氏名",
    "ファイル名称"
    ]

    MJS法人税3 = [    
    "URL",
    "ページ",
    "法人市民税(均等割)申告納付税額",
    "利用者ID",
    "コード",
    "氏名又は名称",
    "発行元名",
    "発行元所属名",
    "発行元電話番号",
    "発信日時",
    "表示期限",
    "受付日時",
    "受付番号",
    "取扱日",
    "手統名",
    "提出先",
    "年度·期別",
    "納税者氏名",
    "ファイル名称"
    ]

    MJS法人税4 = [  
    "URL", 
    "ページ",
    "法人事業税所得金額総額",
    "法人県民税(均等割)申告納付税額",
    "利用者ID",
    "コード",
    "氏名又は名称",
    "発行元名",
    "発行元所属名",
    "発行元電話番号",
    "発信日時",
    "表示期限",
    "受付日時",
    "受付番号",
    "取扱日",
    "手統名",
    "提出先",
    "年度·期別",
    "納税者氏名",
    "ファイル名称"
    ]

    MJS所得税 = [
    "URL", 
    "ページ",    
    "手続名",
    "提出先",
    "利用者識別番号",
    "コード",
    "氏名又は名称",
    "受付番号",
    "受付日時",
    "年分",
    "種目",
    "所得金額",
    "第3期分の税額納める税金",
    "第3期分の税額還付される税金"
    ]

    MJS所得税2 = [
    "URL", 
    "ページ",    
    "提出先",
    "利用者識別番号",
    "コード",
    "氏名又は名称",
    "受付番号",
    "受付日時",
    "年分",
    "種目",
    "所得金額",
    "第3期分の税額納める税金",
    "第3期分の税額還付される税金",
    "備考"
    ]

    MJS所得税3 = [
    "URL", 
    "ページ",    
    "手続名",
    "提出先",
    "利用者識別番号",
    "コード",
    "氏名又は名称",
    "受付番号",
    "受付日時",
    "年分",
    "種目",
    "所得金額",
    "第3期分の税額納める税金"
    ]


    MJS所得税4 = [
    "URL", 
    "ページ",    
    "手続名",
    "提出先",
    "利用者識別番号",
    "コード",
    "氏名又は名称",
    "受付番号",
    "受付日時",
    "年分",
    "種目",
    "所得金額",
    "第3期分の税額納める税金",
    "第3期分の税額還付される税金",
    "備考"
    ]


    MJS所得税5 = [
    "URL", 
    "ページ",    
    "手続名",
    "提出先",
    "利用者識別番号",
    "コード",
    "氏名又は名称",
    "受付番号",
    "受付日時",
    "年分",
    "種目",
    "所得金額",
    "第3期分の税額納める税金",
    "備考"
    ]


    MJS所得税6 = [
    "URL", 
    "ページ",    
    "手続名",
    "提出先",
    "利用者識別番号",
    "コード",
    "氏名又は名称",
    "受付番号",
    "受付日時",
    "年分",
    "種目",
    "第3期分の税額納める税金",
    "第3期分の税額還付される税金",
    "備考",
    "「所得金額」欄について"
    ]


    MJS所得税7 = [
    "URL", 
    "ページ",    
    "手続名",
    "提出先",
    "コード",
    "氏名又は名称",
    "受付番号",
    "受付日時",
    "年分",
    "種目",
    "第3期分の税額還付される税金",
    "備考",
    "「所得金額」欄について"
    ]


    MJS所得税8 = [
    "URL", 
    "ページ",    
    "提出先",
    "利用者識別番号",
    "コード",
    "氏名又は名称",
    "受付日時",
    "年分",
    "種目",
    "第3期分の税額還付される税金",
    "「所得金額」欄について"
    ]


    MJS所得税9 = [
    "URL", 
    "ページ",    
    "手続名",
    "提出先",
    "利用者識別番号",
    "コード",
    "氏名又は名称",
    "受付番号",
    "受付日時",
    "年分",
    "種目",
    "申告納税額還付される税金",
    "「所得金額」欄について"
    ]


    MJS所得税10 = [
    "URL", 
    "ページ",    
    "手続名",
    "提出先",
    "利用者識別番号",
    "コード",
    "氏名又は名称",
    "受付日時",
    "年分",
    "種目",
    "第3期分の税額納める税金",
    "第3期分の税額還付される税金",
    "「所得金額」欄について"
    ]


    MJS所得税11 = [
    "URL", 
    "ページ",    
    "手続名",
    "提出先",
    "コード",
    "氏名又は名称",
    "受付番号",
    "受付日時",
    "年分",
    "種目",
    "申告納税額還付される税金",
    "備考",
    "「所得金額」欄について"
    ]


    MJS所得税12 = [
    "URL", 
    "ページ",    
    "手続名",
    "提出先",
    "利用者識別番号",
    "コード",
    "氏名又は名称",
    "受付日時",
    "年分",
    "種目",
    "第3期分の税額還付される税金",
    "「所得金額」欄について"
    ]


    MJS所得税13 = [
    "URL", 
    "ページ",    
    "手続名",
    "提出先",
    "利用者識別番号",
    "コード",
    "氏名又は名称",
    "受付番号",
    "受付日時",
    "年分",
    "種目",
    "第3期分の税額還付される税金",
    "「所得金額」欄について"
    ]


    MJS所得税14 = [
    "URL", 
    "ページ",    
    "手続名",
    "提出先",
    "利用者識別番号",
    "コード",
    "氏名又は名称",
    "受付番号",
    "受付日時",
    "年分",
    "種目",
    "所得金額",
    "申告納税額納める税金",
    "申告納税額還付される税金",
    "「所得金額」欄について"
    ]


    MJS所得税15 = [
    "URL", 
    "ページ",    
    "手続名",
    "提出先",
    "利用者識別番号",
    "コード",
    "氏名又は名称",
    "受付番号",
    "受付日時",
    "年分",
    "種目",
    "所得金額",
    "申告納税額納める税金",
    "申告納税額還付される税金",
    "備考",
    "「所得金額」欄について"
    ]


    MJS所得税16 = [
    "URL", 
    "ページ",    
    "手続名",
    "提出先",
    "利用者識別番号",
    "コード",
    "氏名又は名称",
    "受付日時",
    "年分",
    "種目",
    "所得金額",
    "第3期分の税額納める税金",
    "第3期分の税額還付される税金",
    "「所得金額」欄について"
    ]


    MJS所得税17 = [
    "URL", 
    "ページ",    
    "手続名",
    "提出先",
    "利用者識別番号",
    "コード",
    "氏名又は名称",
    "受付番号",
    "受付日時",
    "年分",
    "種目",
    "所得金額",
    "第3期分の税額納める税金",
    "第3期分の税額還付される税金",
    "「所得金額」欄について"
    ]


    MJS所得税18 = [
    "URL", 
    "ページ",    
    "手続名",
    "提出先",
    "利用者識別番号",
    "コード",
    "氏名又は名称",
    "受付番号",
    "受付日時",
    "年分",
    "種目",
    "所得金額",
    "第3期分の税額納める税金",
    "第3期分の税額還付される税金",
    "備考",
    "「所得金額」欄について"
    ]


    MJS所得税19 = [
    "URL", 
    "ページ",    
    "提出先",
    "利用者識別番号",
    "コード",
    "氏名又は名称",
    "受付番号",
    "受付日時",
    "年分",
    "種目",
    "所得金額",
    "第3期分の税額納める税金",
    "第3期分の税額還付される税金",
    "備考",
    "「所得金額」欄について"
    ]


    MJS所得税20 = [
    "URL", 
    "ページ",    
    "提出先",
    "利用者識別番号",
    "コード",
    "氏名又は名称",
    "受付番号",
    "受付日時",
    "年分",
    "種目",
    "所得金額",
    "第3期分の税額納める税金",
    "第3期分の税額還付される税金",
    "「所得金額」欄について"
    ]


    MJS消費税 = [
    "URL",
    "ページ",
    "手続名",
    "提出先",
    "利用者識別番号",
    "コード",
    "氏名又は名称",
    "受付番号",
    "受付日時",
    "課税期間自",
    "課税期間至",
    "種目",
    "課税標準額",
    "消費税及び地方消費税の合計(納",
    "備考"
    ]

    MJS消費税2 = [
    "URL",
    "ページ",
    "提出先",
    "利用者識別番号",
    "コード",
    "氏名又は名称",
    "受付番号",
    "受付日時",
    "課税期間自",
    "課税期間至",
    "種目",
    "課税標準額",
    "消費税及び地方消費税の合計(納",
    "備考"
    ]


    MJS消費税3 = [
    "URL",
    "ページ",
    "提出先",
    "手続名",
    "提出先",
    "利用者識別番号",
    "コード",
    "氏名又は名称",
    "受付番号",
    "受付日時",
    "課税期間自",
    "課税期間至",
    "種目",
    "課税標準額",
    "消費税及び地方消費税の合計(納",
    "備考"
    ]

    MJSイメージ = [
    "URL",
    "ページ",
    "手続名",
    "提出先",
    "利用者識別番号",
    "元の申告・申請書の受付番号",
    "コード",
    "氏名又は名称",
    "受付番号",
    "受付日時"
    ]


    etax所得税 = [
    "URL", 
    "ページ",    
    "提出先",
    "利用者識別番号",
    "コード",
    "氏名又は名称",
    "受付番号",
    "受付日時",
    "年分",
    "種目",
    "所得金額",
    "第3期分の税額納める税金",
    "備考"
    ]


    etax所得税2 = [
    "URL", 
    "ページ",    
    "提出先",
    "利用者識別番号",
    "コード",
    "氏名又は名称",
    "受付番号",
    "受付日時",
    "課税期間",
    "種目",
    "課税標準額",
    "消費税及び地方消費税の合計(納付又は還付)税",
    "備考"
    ]


    etax消費税 = [
    "URL", 
    "ページ",    
    "提出先",
    "利用者識別番号",
    "コード",
    "氏名又は名称",
    "受付番号",
    "受付日時",
    "課税期間",
    "種目",
    "課税標準額",
    "備考"
    ]

    eltax法人税 = [
    "URL", 
    "ページ",    
    "発行元",
    "発行元部署",
    "電話番号",
    "発行日時",
    "表示期限",
    "件名",
    "受付日時",
    "受付番号",
    "手続名",
    "提出先"
    ]

    eltax法人税2 = [
    "URL", 
    "ページ",    
    "発行元",
    "発行元部署",
    "電話番号",
    "発行日時",
    "表示期限",
    "件名",
    "受付日時",
    "受付番号",
    "手続名",
    "提出先",
    "課税地"
    ]


    eltax法人税3 = [
    "URL", 
    "ページ",    
    "発行元",
    "発行元部署",
    "電話番号",
    "発行日時",
    "表示期限",
    "件名",
    "法人事業税所得金額総額", 
    "法人事業税申告納付税額",
    "特別法人事業税申告納付税額",
    "法人県民税(法人税割)課税標準総額",
    "法人県民税(法人税割)申告納付税額",
    "法人県民税(均等割)申告納付税額",
    "受付日時",
    "受付番号",
    "手続名",
    "提出先",
    ]


    eltax法人税4 = [
    "URL", 
    "ページ",    
    "発行元",
    "発行元部署",
    "電話番号",
    "発行日時",
    "表示期限",
    "件名",
    "法人市民税(法人税割)課税標準総額", 
    "法人市民税(法人税割)申告納付税額", 
    "法人市民税(均等割)申告納付税額",
    "受付日時",
    "受付番号",
    "手続名",
    "提出先",
    ]


    eltax法人税5 = [
    "URL", 
    "ページ",    
    "発行元",
    "発行元部署",
    "電話番号",
    "発行日時",
    "表示期限",
    "件名",
    "法人事業税所得金額総額",
    "法人県民税(均等割)申告納付税額",
    "受付日時",
    "受付番号",
    "手続名",
    "提出先",
    ]


    eltax法人税6 = [
    "URL", 
    "ページ",    
    "発行元",
    "発行元部署",
    "電話番号",
    "発行日時",
    "表示期限",
    "件名",
    "法人市民税(均等割)申告納付税額",
    "受付日時",
    "受付番号",
    "手続名",
    "提出先",
    ]


    エラーリスト = [
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
    "10",
    "11",
    "12",
    "13",
    "14",
    "15",
    "16",
    "17",
    "18",
    "19",
    "20"
    ]