[MASTER]
#------------------------------------------------
    ListNameList = [
    "MJS法人税",
    "MJS法人税2",
    "MJS法人税3",
    "MJS法人税4",
    ]
#------------------------------------------------
[AIOCR]
#------------------------------------------------
    MJS法人税 = [
    "URL",
    "ページ",
    "法人事業税所得金額総額", 
    "法人県民税(均等割)申告納付税額",
    "利用者ID",
    "コード", 
    "氏名又は名称",
    "発行元名", 
    "発行元所属名",
    "発行元電話番号",
    "発信日時",
    "表示期限",
    "受付日時",
    "受付番号",
    "取扱日",
    "手統名",
    "提出先",
    "年度·期別",
    "納税者氏名",
    "ファイル名称"
    ]

    MJS法人税2 = [    
    "URL",
    "ページ",
    "法人事業税所得金額総額",
    "法人事業税申告納付税額",
    "特別法人事業税申告納付税額",
    "法人県民税(法人税制)課税標準総額",
    "法人県民税(法人税制)申告納付税額",
    "法人県民税(均等割)申告納付税額",
    "利用者ID",
    "コード",
    "氏名又は名称",
    "発行元名",
    "発行元所属名",
    "発行元電話番号",
    "张信日時",
    "表示期限",
    "受付日時",
    "受付番号",
    "取报日",
    "手統名",
    "提出先",
    "年度·期別",
    "納税者氏名",
    "ファイル名称"
    ]

    MJS法人税3 = [    
    "URL",
    "ページ",
    "法人市民税(均等割)申告納付税額",
    "利用者ID",
    "コード",
    "氏名又は名称",
    "発行元名",
    "発行元所属名",
    "発行元電話番号",
    "発信日時",
    "表示期限",
    "受付日時",
    "受付番号",
    "取扱日",
    "手統名",
    "提出先",
    "年度·期別",
    "納税者氏名",
    "ファイル名称",
    ]

    MJS法人税4 = [  
    "URL", 
    "ページ",
    "法人事業税所得金額総額",
    "法人県民税(均等割)申告納付税額",
    "利用者ID",
    "コード",
    "氏名又は名称",
    "発行元名",
    "発行元所属名",
    "発行元電話番号",
    "発信日時",
    "表示期限",
    "受付日時",
    "受付番号",
    "取扱日",
    "手統名",
    "提出先",
    "年度·期別",
    "納税者氏名",
    "ファイル名称",
    ]