[AIOCR]
#------------------------------------------------
    eTax源泉所得税及復興特別所得税 = [
    "利用者識別番号",
    "氏名又は名称",
    "受付番号",
    "受付日時",
    "納付先",
    "税目",
    "申告区分",
    "課税期間",
    "課税期間",
    "合計金額",
    "徴収高計算書の送付の要否"
    ]
    eTax源泉所得税及復興特別所得税削除対象項目 = [
    "利用者識別番号",
    "氏名又は名称",
    "受付番号",
    "受付日時",
    "納付先",
    "税目",
    "申告区分",
    "課税期間",
    "合計金額",
    "徴収高計算書の送付の要否"
    ]
#------------------------------------------------
    eTax源泉所得税及復興特別所得税2 = [
    "提出先",
    "利用者識別番号",
    "氏名又は名称",
    "受付番号",
    "受付日時",
    "年分",
    "種目",
    "所得金額",
    "納める税金",
    "還付される税金"
    ]
    eTax源泉所得税及復興特別所得税2削除対象項目 = [
    "提出先",
    "利用者識別番号",
    "氏名又は名称",
    "受付番号",
    "受付日時",
    "年分",
    "種目",
    "所得金額",
    "第3期分の税額",
    "納める税金",
    "還付される税金",
    "備考",
    "「所得金額」欄について"
    ]
#------------------------------------------------
    eTax消費税中間申告用 = [
    "削除",
    "利用者識別番号", 
    "整理番号", 
    "氏名又は名称",
    "納税者氏名",
    "納付先",
    "削除",
    "削除",
    "前課税期間",
    "前課税期間",
    "修正·更正·決定の年月日",
    "削除",
    "前課税期間の消費税額",
    "中間申告対象期間", 
    "中間申告対象期間",  
    "前課税期間の消費税額割合",
    "前課税期間の消費税額割合",
    "納付すべき消費税額",
    "納付すべき地方消費税額", 
    "消費税及び地方消費税の合計納付税額"
    ]
    eTax消費税中間申告用削除対象項目 = [
    "利用者識別番号",
    "整理番号",
    "前課税期間",
    "修正·更正·決定の年月日", 
    "前課税期間の消費税額",
    "中間申告対象期間",
    "月数換算",
    "前課税期間の消費税額",
    "納付すべき消費税額",
    "納付すべき地方消費税額",
    "消費税及び地方消費税の合計納付税額"
    ]
#------------------------------------------------
    MJS所得税 = [
    "提出先",
    "利用者識別番号",
    "氏名又は名称",
    "受付番号",
    "受付日時",
    "年分",
    "種目",
    "所得金額",
    "第3期分の税額納める税金",
    "第3期分の税額還付される税金"
    ]
    MJS所得税削除対象項目 = [
    "提出先",
    "利用者識別番号",
    "氏名又は名称",
    "受付番号",
    "受付日時",
    "年分",
    "種目",
    "所得金額",
    "第3期分の税額納める税金",
    "第3期分の税額還付される税金",
    "備考", 
    "「所得金額」欄について"
    ]
#------------------------------------------------
    MJS所得税2 = [
    "手続名",
    "提出先",
    "利用者識別番号",
    "氏名又は名称",
    "受付番号",
    "受付日時",
    "年分",
    "種目",
    "所得金額",
    "第3期分の税額納める税金",
    "第3期分の税額還付される税金"
    ]
    MJS所得税2削除対象項目 = [
    "手続名",
    "提出先",
    "利用者識別番号",
    "氏名又は名称",
    "受付番号",
    "受付日時",
    "年分",
    "種目",
    "所得金額",
    "第3期分の税額納める税金",
    "第3期分の税額還付される税金",
    "「所得金額」欄について"
    ]
#------------------------------------------------
    MJS消費税 = [
    "提出先",
    "利用者識別番号",
    "氏名又は名称",
    "受付番号",
    "受付日時",
    "課税期間自",
    "課税期間至",
    "種目",
    "課税標準額",
    "消費税及び地方消費税の合計(納付又は還付)税額"
    ]
    MJS消費税削除対象項目 = [
    "提出先",
    "利用者識別番号",
    "氏名又は名称",
    "受付番号",
    "受付日時",
    "課税期間自",
    "課税期間至",
    "種目",
    "課税標準額",
    "消費税及び地方消費税の合計(納",
    "付又は還付)税額",
    "備考"
    ]
#------------------------------------------------
    MJS消費税2 = [
    "手続名",
    "提出先",
    "利用者識別番号",
    "氏名又は名称",
    "受付番号",
    "受付日時",
    "課税期間自",
    "課税期間至",
    "種目",
    "課税標準額",
    "消費税及び地方消費税の合計(納付又は還付)税額"
    ]
    MJS消費税2削除対象項目 = [
    "手続名",
    "提出先",
    "利用者識別番号",
    "氏名又は名称",
    "受付番号",
    "受付日時",
    "課税期間自",
    "課税期間至",
    "種目",
    "課税標準額",
    "消費税及び地方消費税の合計(納",
    "付又は還付)税額",
    "備考"
    ]