[ListSetting]
Columns = [
    "列番号",
    "列番号2",
    "列番号3",
]
Index = [
    "日付列",
    "金額列",
    "変換対象列",
]
"日付列" = [
    "1",
]
"金額列" = [
    "3",
    "4",
    "5",
]
"変換対象列" = [
    "2",
    "3",
    "4",
]

[ColumnSetting]
Index = [
    "日付列名",
    "入金列名",
    "出金列名",
    "残高列名",
    "自動仕訳基準列名",
    "自動仕訳検索範囲月",
]
"日付列名" = [
    "日付",
]
"入金列名" = [
    "入金",
]
"出金列名" = [
    "出金",
]
"残高列名" = [
    "残高",
]
"自動仕訳基準列名" = [
    "摘要",
]
"自動仕訳検索範囲月" = [
    "1",
]

[OCR_ListSetting]
Columns = [
    "列番号",
    "列番号2",
    "列番号3",
]
Index = [
    "日付列",
    "金額列",
    "変換対象列",
]
"日付列" = [
    "1",
]
"金額列" = [
    "3",
    "4",
    "5",
]
"変換対象列" = [
    "2",
    "3",
    "4",
]

[OCR_ColumnSetting]
Columns = [
    "列名",
]
Index = [
    "日付列名",
    "入金列名",
    "出金列名",
    "残高列名",
    "自動仕訳基準列名",
    "自動仕訳検索範囲月",
]
"日付列名" = [
    "日付",
]
"入金列名" = [
    "入金",
]
"出金列名" = [
    "出金",
]
"残高列名" = [
    "残高",
]
"自動仕訳基準列名" = [
    "摘要",
]
"自動仕訳検索範囲月" = [
    "1",
]
