[MASTER]
#------------------------------------------------
    ListNameList = [
    "etaxsyotoku",
    "etaxsyotoku2",
    "etaxsyotoku3",
    "etaxsyotoku4",
    "etaxsyotoku5",
    "etaxosirase",
    "eltaxList",
    "eltaxList2",
    "eltaxList3",
    "eltaxList4",
    "eltaxPreList",
    "etaxsyouhitodoke",
    "etaxjigyounendo",
    "etaximage",
    "etaxnouhu",
    "etaxnouhu2",
    "ErrList"
    ]
[CsvSaveEnc]
    etaxsyotoku = [
    "URL",
    "ページ",
    "コード", 
    "利用者識別番号",
    "氏名（名称）",
    "受付番号",
    "納付年月日",
    "納付先",
    "税目",
    "申告区分",
    "課税期間（自）",
    "課税期間（至）",
    "金融機関",
    "納付金額"
    ]


    etaxsyotoku2 = [
    "URL",
    "ページ",
    "コード", 
    "利用者識別番号",
    "氏名又は名称",
    "代表者等氏名",
    "受付番号",
    "受付日時",
    "納付先",
    "税目",
    "申告区分",
    "課税期間",
    "",
    "合計金額",
    "徴収高計算書の送付の要否"
    ]


    etaxsyotoku3 = [
    "URL",
    "ページ",
    "コード", 
    "利用者識別番号",
    "氏名又は名称",
    "受付番号",
    "受付日時",
    "納付先",
    "税目",
    "申告区分",
    "課税期間",
    "",
    "合計金額",
    "徴収高計算書の送付の要否"
    ]


    etaxsyotoku4 = [
    "URL",
    "ページ",
    "コード",
    "提出先", 
    "利用者識別番号",
    "氏名又は名称",
    "代表者等氏名",
    "受付番号",
    "受付日時",
    "種目",
    "事業年度 自",
    "事業年度 至",
    "税目",
    "申告の種類",
    "所得金額又は欠損金額",
    "この申告による還付金額",
    "欠損金又は災害損失金等の当期控除額",
    "翌期へ繰り越す欠損金又は災害損失金",
    "税目",
    "申告の種類",
    "課税標準法人税額",
    "差引確定地方法人税額"
    ]


    etaxsyotoku5 = [
    "URL",
    "ページ",
    "コード",
    "提出先", 
    "利用者識別番号",
    "氏名又は名称",
    "代表者等氏名",
    "受付番号",
    "受付日時",
    "種目",
    "事業年度 自",
    "事業年度 至",
    "税目",
    "申告の種類",
    "所得金額又は欠損金額",
    "差引確定法人税額",
    "欠損金又は災害損失金等の当期控除額",
    "翌期へ繰り越す欠損金又は災害損失金",
    "税目",
    "申告の種類",
    "課税標準法人税額",
    "差引確定地方法人税額"
    ]


    etaxosirase = [
    "URL",
    "ページ",
    "コード", 
    "利用者識別番号",
    "項目",
    "整理番号",
    "業種番号",
    "社名",
    "氏名",
    "相手氏名",
    "件名"
    ]


    eltaxList = [
    "URL",
    "ページ",
    "コード", 
    "発行元",
    "項目",
    "電話番号",
    "項目",
    "表示期限",
    "件名", 
    "項目",
    "取扱日", 
    "受付番号", 
    "手続名",
    "年度・期別等",
    "提出先",
    "課税地"
    ]


    eltaxList2 = [
    "URL",
    "ページ",
    "コード", 
    "発行元",
    "項目",
    "電話番号",
    "項目",
    "表示期限",
    "件名",
    "リンク先", 
    "項目",
    "取扱日", 
    "受付番号", 
    "手続名",
    "年度・期別等",
    "提出先",
    "課税地",
    "ファイル名称"
    ]



    eltaxList3 = [
    "URL",
    "ページ",
    "コード", 
    "発行元",
    "項目",
    "電話番号",
    "項目",
    "表示期限",
    "件名",
    "受付日時", 
    "受付番号", 
    "手続名",
    "提出先"
    ]


    eltaxList4 = [
    "URL",
    "ページ",
    "コード", 
    "発行元",
    "項目",
    "電話番号",
    "項目",
    "表示期限",
    "件名",
    "メッセージ本文",
    "リンク先", 
    "項目",
    "取扱日", 
    "受付番号", 
    "手続名",
    "年度・期別等",
    "提出先",
    "課税地",
    "ファイル名称"
    ]


    eltaxPreList = [
    "URL",
    "ページ",
    "コード", 
    "発行元",
    "電話番号",
    "項目",
    "表示期限",
    "件名", 
    "リンク先"
    ]


    etaxsyouhitodoke = [
    "URL",
    "ページ",
    "コード", 
    "提出先",
    "利用者識別番号",
    "氏名又は名称",
    "代表者等氏名",
    "受付番号",
    "受付日時",
    "種目"
    ]


    etaxjigyounendo = [
    "URL",
    "ページ",
    "コード", 
    "前事業年度等",
    "前事業年度等",
    "修正・更正・決定の年月日",
    "修正・更正・決定の年月日",
    "前事業年度の法人税額",
    "前課税事業年度の地方法人税額",
    "同上のうち土地譲渡税額等及",
    "同上のうち土地譲渡税額等及",
    "差引法人税額",
    "差引地方法人税額",
    "納付すべき法人税額",
    "納付すべき地方法人税額"
    ]


    etaximage = [
    "URL",
    "ページ",
    "コード", 
    "提出先",
    "利用者識別番号",
    "元の申告・申請書の受付番号",
    "氏名又は名称",
    "代表者等氏名",
    "受付番号",
    "受付日時",
    ]


    etaxnouhu = [
    "URL",
    "ページ",
    "コード", 
    "利用者識別番号",
    "氏名又は名称",
    "代表者等氏名",
    "受付番号",
    "受付日時",
    "納付先",
    "税目",
    "申告区分",
    "課税期間",
    "",
    "合計金額"
    ]


    etaxnouhu2 = [
    "URL",
    "ページ",
    "コード", 
    "利用者識別番号",
    "氏名又は名称",
    "代表者等氏名",
    "受付番号",
    "受付日時",
    "納付先",
    "税目",
    "申告区分（法人税）",
    "申告区分（地方法人税）",
    "課税期間",
    "",
    "合計金額"
    ]


    ErrList = [
    "URL",
    "ページ",
    "コード", 
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
    "10",
    "11",
    "12",
    "13",
    "14",
    "15",
    "16",
    "17",
    "18",
    "19",
    "20"
    ]