[MASTER]
#------------------------------------------------
    ListNameList = [
    "etaxsyotoku",
    "etaxsyotoku2",
    "etaxsyotoku3",
    "etaxsyotoku4",
    "etaxsyotoku5",
    "etaxosirase",
    "eltaxList",
    "eltaxList2",
    "eltaxList3",
    "eltaxList4",
    "eltaxList5",
    "eltaxPreList",
    "eltaxPreList2",
    "etaxsyouhitodoke",
    "etaxjigyounendo",
    "etaximage",
    "etaxnouhu",
    "etaxnouhu2",
    "etaxsyouhicyuukan",
    "etaxsyouhisinkoku",
    "TKC",
    "TKC2",
    "TKC3",
    "TKC4",
    "TKC5",
    "TKC6",
    "TKC7",
    "TKC8",
    "MJS",
    "MJS2",
    "MJS3",
    "MJS4",
    "ErrList",
    "SubErrList"
    ]
[CsvSaveEnc]
    etaxsyotoku = [
    "URL",
    "ページ",
    "コード",
    "利用者識別番号",
    "氏名（名称）",
    "受付番号",
    "納付年月日",
    "納付先",
    "税目",
    "申告区分",
    "課税期間（自）",
    "課税期間（至）",
    "金融機関",
    "納付金額"
    ]


    etaxsyotoku2 = [
    "URL",
    "ページ",
    "コード",
    "利用者識別番号",
    "氏名又は名称",
    "代表者等氏名",
    "受付番号",
    "受付日時",
    "納付先",
    "税目",
    "申告区分",
    "課税期間",
    "",
    "合計金額",
    "徴収高計算書の送付の要否"
    ]


    etaxsyotoku3 = [
    "URL",
    "ページ",
    "コード",
    "利用者識別番号",
    "氏名又は名称",
    "受付番号",
    "受付日時",
    "納付先",
    "税目",
    "申告区分",
    "課税期間",
    "",
    "合計金額",
    "徴収高計算書の送付の要否"
    ]


    etaxsyotoku4 = [
    "URL",
    "ページ",
    "コード",
    "提出先",
    "利用者識別番号",
    "氏名又は名称",
    "代表者等氏名",
    "受付番号",
    "受付日時",
    "種目",
    "事業年度自",
    "事業年度至",
    "税目",
    "申告の種類",
    "所得金額又は欠損金額",
    "この申告による還付金額",
    "欠損金又は災害損失金等の当期控除額",
    "翌期へ繰り越す欠損金又は災害損失金",
    "税目",
    "申告の種類",
    "課税標準法人税額",
    "差引確定地方法人税額"
    ]


    etaxsyotoku5 = [
    "URL",
    "ページ",
    "コード",
    "提出先",
    "利用者識別番号",
    "氏名又は名称",
    "代表者等氏名",
    "受付番号",
    "受付日時",
    "種目",
    "事業年度自",
    "事業年度至",
    "税目",
    "申告の種類",
    "所得金額又は欠損金額",
    "差引確定法人税額",
    "欠損金又は災害損失金等の当期控除額",
    "翌期へ繰り越す欠損金又は災害損失金",
    "税目",
    "申告の種類",
    "課税標準法人税額",
    "差引確定地方法人税額"
    ]


    etaxosirase = [
    "URL",
    "ページ",
    "コード",
    "利用者識別番号",
    "項目",
    "整理番号",
    "業種番号",
    "社名",
    "氏名",
    "相手氏名",
    "件名"
    ]


    eltaxList = [
    "URL",
    "ページ",
    "コード",
    "発行元",
    "項目",
    "電話番号",
    "項目2",
    "表示期限",
    "件名",
    "項目3",
    "取扱日",
    "受付番号",
    "手続名",
    "年度・期別等",
    "提出先",
    "課税地"
    ]


    eltaxList2 = [
    "URL",
    "ページ",
    "コード",
    "発行元",
    "項目",
    "電話番号",
    "項目2",
    "表示期限",
    "件名",
    "リンク先",
    "項目3",
    "取扱日",
    "受付番号",
    "手続名",
    "年度・期別等",
    "提出先",
    "課税地",
    "ファイル名称"
    ]



    eltaxList3 = [
    "URL",
    "ページ",
    "コード",
    "発行元",
    "項目",
    "電話番号",
    "項目2",
    "表示期限",
    "件名",
    "受付日時",
    "受付番号",
    "手続名",
    "提出先"
    ]


    eltaxList4 = [
    "URL",
    "ページ",
    "コード",
    "発行元",
    "項目",
    "電話番号",
    "項目2",
    "表示期限",
    "件名",
    "メッセージ本文",
    "リンク先",
    "項目3",
    "取扱日",
    "受付番号",
    "手続名",
    "年度・期別等",
    "提出先",
    "課税地",
    "ファイル名称"
    ]


    eltaxList5 = [
    "URL",
    "ページ",
    "コード",
    "発行元",
    "電話番号",
    "項目",
    "表示期限",
    "件名",
    "項目2",
    "取扱日",
    "受付番号",
    "手続名",
    "年度・期別等",
    "提出先",
    "課税地"
    ]


    eltaxPreList = [
    "URL",
    "ページ",
    "コード",
    "発行元",
    "項目",
    "電話番号",
    "項目2",
    "表示期限",
    "件名",
    "リンク先"
    ]


    eltaxPreList2 = [
    "URL",
    "ページ",
    "コード",
    "発行元",
    "電話番号",
    "項目",
    "表示期限",
    "件名",
    "リンク先"
    ]


    etaxsyouhitodoke = [
    "URL",
    "ページ",
    "コード",
    "提出先",
    "利用者識別番号",
    "氏名又は名称",
    "代表者等氏名",
    "受付番号",
    "受付日時",
    "種目"
    ]


    etaxjigyounendo = [
    "URL",
    "ページ",
    "コード",
    "前事業年度等",
    "前事業年度等",
    "修正・更正・決定の年月日",
    "修正・更正・決定の年月日",
    "前事業年度の法人税額",
    "前課税事業年度の地方法人税額",
    "同上のうち土地譲渡税額等及",
    "同上のうち土地譲渡税額等及",
    "差引法人税額",
    "差引地方法人税額",
    "納付すべき法人税額",
    "納付すべき地方法人税額"
    ]


    etaximage = [
    "URL",
    "ページ",
    "コード",
    "提出先",
    "利用者識別番号",
    "元の申告・申請書の受付番号",
    "氏名又は名称",
    "代表者等氏名",
    "受付番号",
    "受付日時",
    ]


    etaxnouhu = [
    "URL",
    "ページ",
    "コード",
    "利用者識別番号",
    "氏名又は名称",
    "代表者等氏名",
    "受付番号",
    "受付日時",
    "納付先",
    "税目",
    "申告区分",
    "課税期間",
    "",
    "合計金額"
    ]


    etaxnouhu2 = [
    "URL",
    "ページ",
    "コード",
    "利用者識別番号",
    "氏名又は名称",
    "代表者等氏名",
    "受付番号",
    "受付日時",
    "納付先",
    "税目",
    "申告区分（法人税）",
    "申告区分（地方法人税）",
    "課税期間",
    "",
    "合計金額"
    ]


    etaxsyouhicyuukan = [
    "URL",
    "ページ",
    "コード",
    "前課税期間",
    "修正・更正・決定の年月日",
    "前課税期間の消費税額",
    "中間申告対象期間",
    "月数換算",
    "納付すべき消費税額",
    "納付すべき地方消費税額",
    "消費税及び地方消費税の合計納付税額"
    ]


    etaxsyouhisinkoku = [
    "URL",
    "ページ",
    "コード",
    "提出先",
    "利用者識別番号",
    "氏名又は名称",
    "代表者等氏名",
    "受付番号",
    "受付日時",
    "種目",
    "申告の種類",
    "課税期間",
    "",
    "課税標準額",
    "消費税及び地方消費税の合計（納付又は還付）税額"
    ]


    TKC = [
    "URL",
    "ページ",
    "コード",
    "提出先",
    "利用者識別番号",
    "氏名又は名称",
    "代表者等氏名",
    "受付番号",
    "受付日時",
    "種目",
    "備考",
    "提出先",
    "利用者識別番号",
    "元の申告・申請書の受付番号",
    "氏名又は名称",
    "代表者等氏名",
    "受付番号",
    "受付日時"
    ]


    TKC2 = [
    "URL",
    "ページ",
    "コード",
    "申請番号",
    "申請・届出者",
    "手続名",
    "受付日"
    ]

    #TKC完了報告書の基準カラムリスト
    TKC3 = [
    "URL",
    "ページ",
    "コード",
    "提出先",
    "利用者識別番号",
    "元の申告・申請書の受付番号",
    "氏名又は名称",
    "代表者等氏名",
    "受付番号",
    "受付日時",
    "種目",
    "事業年度自",
    "事業年度至",
    "課税期間自",
    "課税期間至",
    "税目",
    "申告の種類",
    "所得金額又は欠損金額",
    "この申告による還付金額",
    "欠損金又は災害損失金等の当期控除額",
    "翌期へ繰り越す欠損金又は災害損失金",
    "消費税及び地方消費税の合計（納付又は還付）税額",
    "税目",
    "申告の種類",
    "課税標準法人税額",
    "この申告による還付金額",
    "発行元",
    "電話番号",
    "発行日時",
    "件名",
    "メッセージ本文",
    "法人事業税所得金額総額",
    "法人事業税申告納付税額",
    "特別法人事業税申告納付税額",
    "法人県民税（法人税割）課税標準総額",
    "法人県民税（法人税割）申告納付税額",
    "法人県民税（均等割）申告納付税額",
    "受付日時",
    "取扱日",
    "受付番号",
    "手続名",
    "事業年度(期別)",
    "提出先",
    "ファイル名称",
    "納税者の氏名又は名称"
    ]


    TKC4 = [
    "URL",
    "ページ",
    "コード",
    "提出先",
    "利用者識別番号",
    "元の申告・申請書の受付番号",
    "氏名又は名称",
    "代表者等氏名",
    "受付番号",
    "受付日時"
    ]


    TKC5 = [
    "URL",
    "ページ",
    "コード",
    "提出先",
    "利用者識別番号",
    "氏名又は名称",
    "代表者等氏名",
    "受付番号",
    "受付日時",
    "種目",
    "申告の種類",
    "課税期間自",
    "課税期間至",
    "消費税及び地方消費税の合計（納付又は還付）税額"
    ]


    TKC6 = [
    "URL",
    "ページ",
    "コード",
    "提出先",
    "利用者識別番号",
    "氏名又は名称",
    "代表者等氏名",
    "受付番号",
    "受付日時",
    "種目",
    "申告の種類"
    ]


    TKC7 = [
    "URL",
    "ページ",
    "コード",
    "提出先",
    "利用者識別番号",
    "氏名又は名称",
    "代表者等氏名",
    "受付番号",
    "受付日時",
    "種目",
    "事業年度自",
    "事業年度至",
    "税目",
    "申告の種類",
    "所得金額又は欠損金額",
    "この申告による還付金額",
    "欠損金又は災害損失金等の当期控除額",
    "翌期へ繰り越す欠損金又は災害損失金",
    "税目",
    "申告の種類",
    "課税標準法人税額",
    "この申告による還付金額"
    ]


    TKC8 = [
    "URL",
    "ページ",
    "コード",
    "納税者の氏名又は名称",
    "発行元",
    "電話番号",
    "発行日時",
    "件名",
    "メッセージ本文",
    "受付日時",
    "取扱日",
    "受付番号",
    "手続名",
    "事業年度(期別)",
    "提出先",
    "ファイル名称"
    ]


    MJS = [
    "URL",
    "ページ",
    "コード",
    "利用者ＩＤ",
    "氏名又は名称",
    "発行元名",
    "発行元所属名",
    "発行元電話番号",
    "発信日時",
    "表示期限",
    "受付日時",
    "受付番号",
    "取扱日",
    "手続名",
    "提出先",
    "年度・期別",
    "納税者氏名",
    "ファイル名称"
    ]


    MJS2 = [
    "URL",
    "ページ",
    "コード",
    "利用者ＩＤ",
    "氏名又は名称",
    "発行元名",
    "発行元所属名",
    "発行元電話番号",
    "発信日時",
    "表示期限",
    "受付日時",
    "受付番号",
    "取扱日",
    "提出先",
    "年度・期別",
    "納税者氏名",
    "ファイル名称"
    ]


    MJS3 = [
    "URL",
    "ページ",
    "コード",
    "手続名",
    "提出先",
    "利用者識別番号",
    "氏名又は名称",
    "代表者等氏名",
    "受付番号",
    "受付日時",
    "種目",
    "申告の種類",
    "課税期間自",
    "課税期間至",
    "課税標準額",
    "消費税及び地方消費税の合計（納付又は還付）税額"
    ]


    MJS4 = [
    "URL",
    "ページ",
    "コード",
    "手続名",
    "提出先",
    "利用者識別番号",
    "氏名又は名称",
    "代表者等氏名",
    "受付番号",
    "受付日時",
    "種目",
    "事業年度自",
    "事業年度至",
    "税目",
    "申告の種類",
    "所得金額又は欠損金額",
    "この申告による還付金額",
    "欠損金又は災害損失金等の当期控除額"
    ]


    ErrList = [
    "URL",
    "ページ",
    "コード",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
    "10",
    "11",
    "12",
    "13",
    "14",
    "15",
    "16",
    "17",
    "18",
    "19",
    "20"
    ]

    SubErrList = [
    "URL",
    "ページ",
    "コード",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
    "10",
    "11",
    "12",
    "13",
    "14"
    ]