[CsvSaveEnc]
    SinkokuCSVList = [
    "コード",
    "URL",
    "ページ",
    "手続名",
    "氏名又は名称",
    "受付日時",
    "種目",
    "事業年度",
    "税目",
    "申告の種類",
    "所得金額又は欠損金額",
    "差引確定法人税額",
    "欠損金又は災害損失金等の当期控除額",
    "翌期へ繰り越す欠損金又は災害損失金",
    "税目2",
    "申告の種類2",
    "課税標準法人税額",
    "差引確定地方法人税額"
    ]
    SinkokuCSV2List = [
    "コード",
    "URL",
    "ページ",
    "手続名",
    "氏名又は名称",
    "受付日時",
    "種目",
    "事業年度",
    "税目",
    "申告の種類",
    "所得金額又は欠損金額",
    "この申告による還付金額",
    "欠損金又は災害損失金等の当期控除額",
    "翌期へ繰り越す欠損金又は災害損失金",
    "税目2",
    "申告の種類2",
    "課税標準法人税額",
    "この申告による還付金額2"
    ]
    SinkokuCSV3List = [
    "コード",
    "URL",
    "ページ",
    "手続名",
    "氏名又は名称",
    "受付日時",
    "種目",
    "事業年度",
    "税目",
    "申告の種類",
    "所得金額又は欠損金額",
    "この申告による還付金額",
    "欠損金又は災害損失金等の当期控除額",
    "翌期へ繰り越す欠損金又は災害損失金",
    "税目2",
    "申告の種類2",
    "課税標準法人税額",
    "差引確定地方法人税額"
    ]
    SinkokuCSV4List = [
    "コード",
    "URL",
    "ページ",
    "手続名",
    "氏名又は名称",
    "受付日時",
    "種目",
    "事業年度",
    "税目",
    "申告の種類",
    "所得金額又は欠損金額",
    "差引確定法人税額",
    "欠損金又は災害損失金等の当期控除額",
    "翌期へ繰り越す欠損金又は災害損失金",
    "税目2",
    "申告の種類2",
    "課税標準法人税額",
    "差引確定地方法人税額"
    ]
    SyotokuCSVList = [
    "コード",
    "URL",
    "ページ",
    "手続名",
    "氏名又は名称",
    "受付日時",
    "年分",
    "種目",
    "所得金額",
    "納める税金",
    "還付される税金"
    ]
    SyotokuCSV2List = [
    "コード",
    "URL",
    "ページ",
    "氏名又は名称",
    "受付日時",
    "年分",
    "種目",
    "所得金額",
    "納める税金",
    "還付される税金",
    "「所得金額」欄について"
    ]
    SyotokuCSV3List = [
    "コード",
    "URL",
    "ページ",
    "手続名",
    "氏名又は名称",
    "受付日時",
    "年分",
    "種目",
    "所得金額",
    "納める税金",
    "還付される税金",
    "「所得金額」欄について"
    ]
    SyotokuCSV4List = [
    "コード",
    "URL",
    "ページ",
    "手続名",
    "氏名又は名称",
    "受付日時",
    "年分",
    "種目",
    "所得金額",
    "納める税金",
    "還付される税金",
    "「所得金額」欄について"
    ]
    SyouhiCSVList = [
    "コード",
    "URL",
    "ページ",
    "手続名",
    "氏名又は名称",
    "受付日時",
    "種目",
    "申告の種類",
    "課税標準額",
    "消費税及び地方消費税の合計",
    "課税期間"
    ]
    SyouhiCSV2List = [
    "コード",
    "URL",
    "ページ",
    "手続名",
    "氏名又は名称",
    "受付日時",
    "種目",
    "課税標準額",
    "消費税及び地方消費税の合計",
    "課税期間"
    ]
    SyouhiCSV3List = [
    "コード",
    "URL",
    "ページ",
    "氏名又は名称",
    "受付日時",
    "種目",
    "課税標準額",
    "消費税及び地方消費税の合計",
    "課税期間"
    ]
    SyouhiCyukanCSVList = [
    "コード",
    "URL",
    "ページ",
    "手続名",
    "氏名又は名称",
    "受付日時",
    "種目",
    "消費税及び地方消費税の合計",
    "課税期間"
    ]
    HoujinCSVList = [
    "コード",
    "URL",
    "ページ",
    "手続名",
    "氏名又は名称",
    "発行元名",
    "発行元所属名",
    "受付日時",
    "提出先",
    "年度・期別",
    "納税者氏名",
    "表外表示金額"
    ]
    HoujinCSV2List = [
    "コード",
    "URL",
    "ページ",
    "手続名",
    "氏名又は名称",
    "受付日時",
    "種目",
    "事業年度",
    "税目",
    "申告の種類",
    "所得金額又は欠損金額",
    "この申告による還付金額",
    "欠損金又は災害損失金等の当期控除額",
    " 翌期へ繰り越す欠損金又は災害損失金",
    "税目2",
    "申告の種類2",
    "課税標準法人税額",
    "差引確定地方法人税額",
    "表外表示金額"
    ]
    HoujinSiminCSVList = [
    "コード",
    "URL",
    "ページ",
    "手続名",
    "氏名又は名称",
    "発行元名",
    "受付日時",
    "提出先",
    "年度・期別",
    "納税者氏名",
    "表外表示金額"
    ]
    YoteiCSVList = [
    "コード",
    "URL",
    "ページ",
    "手続名",
    "氏名又は名称",
    "受付日時",
    "種目",
    "事業年度",
    "税目",
    "納付すべき法人税額",
    "税目2",
    "納付すべき地方法人税額"
    ]
    SyoukyakuCSVList = [
    "コード",
    "URL",
    "ページ",
    "手続名",
    "氏名又は名称",
    "発行元名",
    "発行元所属名",
    "受付日時",
    "提出先",
    "年度・期別",
    "課税所在地"
    ]
    SyoukyakuCSV2List = [
    "コード",
    "URL",
    "ページ",
    "手続名",
    "氏名又は名称",
    "発行元名",
    "受付日時",
    "提出先",
    "年度・期別",
    "課税所在地"
    ]
    ZouyoCSVList = [
    "コード",
    "URL",
    "ページ",
    "手続名",
    "氏名又は名称",
    "受付日時",
    "年分",
    "種目",
    "課税価格の合計額",
    "申告期限までに納付すべき税額"
    ]
    ZaisanCSVList = [
    "コード", "URL", "ページ", "手続名", "氏名又は名称", "受付日時", "種目"]
    SinkokuUkeCSVList = [
    "コード",
    "URL",
    "ページ",
    "手続名",
    "氏名又は名称",
    "発行元名",
    "発行元所属名",
    "発行元電話番号",
    "受付日時",
    "提出先",
    "年度・期別",
    "課税所在地"
    ]
    TKCListSinsei = [
    "コード",
    "URL",
    "ページ",
    "提出先",
    "利用者識別番号",
    "氏名又は名称",
    "代表者等氏名",
    "受付番号",
    "受付日時",
    "種目"
    ]
    TKCListHTS = [
    "コード",
    "URL",
    "ページ",
    "提出先",
    "利用者識別番号",
    "氏名又は名称",
    "代表者等氏名",
    "受付番号",
    "受付日時",
    "種目",
    "事業年度",
    "税目",
    "申告の種類",
    "所得金額又は欠損金額",
    "この申告による還付金額",
    "欠損金又は災害損失金等の当期控除額",
    "翌期へ繰り越す欠損金又は災害損失金",
    "税目2",
    "申告の種類2",
    "課税標準法人税額",
    "差引確定地方法人税額"
    ]
    TKCListHTPDF = [
    "コード",
    "URL",
    "ページ",
    "提出先",
    "利用者識別番号",
    "元の申告・申請書の受付番号",
    "氏名又は名称",
    "代表者等氏名",
    "受付番号",
    "受付日時"
    ]
    TKCListSyouhi = [
    "コード",
    "URL",
    "ページ",
    "提出先",
    "利用者識別番号",
    "氏名又は名称",
    "代表者等氏名",
    "受付番号",
    "受付日時",
    "種目",
    "申告の種類",
    "課税期間",
    "課税標準額",
    "消費税合計税額"
    ]
    TKCListSyouhiPDF = [
    "コード", "URL", "ページ", "提出先", "利用者識別番号", "氏名又は名称", "代表者等氏名", "受付番号", "受付日時"]
    TKCListTodouhu = [
    "コード",
    "URL",
    "ページ",
    "納税者の氏名又は名称",
    "発行元",
    "電話番号",
    "発行日時",
    "件名",
    "メッセージ本文金額",
    "受付日時",
    "受付番号",
    "手続名",
    "事業年度",
    "提出先"
    ]
    TKCListSityou = [
    "コード",
    "URL",
    "ページ",
    "納税者の氏名又は名称",
    "発行元",
    "電話番号",
    "発行日時",
    "件名",
    "メッセージ本文金額",
    "受付日時",
    "受付番号",
    "手続名",
    "事業年度",
    "提出先"
    ]
    ImageCSVList = [
    "コード", "URL", "ページ", "手続名", "氏名又は名称", "受付番号", "受付日時", "元の申告・申請書の受付番号"]
    CSVBadList = [
    "コード",
    "URL",
    "ページ",
    "手続名",
    "氏名又は名称",
    "発行元名",
    "発行元所属名",
    "受付日時",
    "提出先",
    "年度・期別",
    "納税者氏名"
    ]
[CSVIndexSort]
    FuncArray = [
    "SCode",
    "path_pdf",
    "SinkokuCSVList",
    "SinkokuCSV2List",
    "SinkokuCSV3List",
    "SinkokuCSV4List",
    "SyotokuCSVList",
    "SyotokuCSV2List",
    "SyotokuCSV3List",
    "SyotokuCSV4List",
    "SyouhiCSVList",
    "SyouhiCSV2List",
    "SyouhiCSV3List",
    "SyouhiCyukanCSVList",
    "HoujinCSVList",
    "HoujinCSV2List",
    "HoujinSiminCSVList",
    "YoteiCSVList",
    "SyoukyakuCSVList",
    "SyoukyakuCSV2List",
    "ZouyoCSVList",
    "ZaisanCSVList",
    "SinkokuUkeCSVList",
    "TKCListSinsei",
    "TKCListHTS",
    "TKCListHTPDF",
    "TKCListSyouhi",
    "TKCListSyouhiPDF",
    "TKCListTodouhu",
    "TKCListSityou",
    "ImageCSVList",
    "CSVBadList",
    "SinkokuCSV",
    "SinkokuCSV2",
    "SinkokuCSV3",
    "SinkokuCSV4",
    "SyotokuCSV",
    "SyotokuCSV2",
    "SyotokuCSV3",
    "SyotokuCSV4",
    "SyouhiCSV",
    "SyouhiCSV2",
    "SyouhiCSV3",
    "SyouhiCyukanCSV",
    "HoujinCSV",
    "HoujinCSV2",
    "HoujinSiminCSV",
    "YoteiCSV",
    "SyoukyakuCSV",
    "SyoukyakuCSV2",
    "ZouyoCSV",
    "ZaisanCSV",
    "SinkokuUkeCSV",
    "ImageCSV",
    ]