[ParList]
Name = [
    "日付列",
    "金額列",
    "変換対象列",
    "日付列名",
    "入金列名",
    "出金列名",
    "残高列名",
    "自動仕訳基準列名",
]
"日付列" = [
    "1",
]
"金額列" = [
    "3",
    "4",
    "5",
]
"変換対象列" = [
    "2",
    "3",
    "4",
]
"日付列名" = "日付"
"入金列名" = "入金"
"出金列名" = "出金"
"残高列名" = "残高"
"自動仕訳基準列名" = "摘要"
"自動仕訳検索範囲月" = [
    "1",
]

[ColList]
Nomal_List = [
    "日付",
    "摘要",
    "出金",
    "入金",
    "残高",
]
Hirogin_1page_List = [
    "日付",
    "摘要",
    "出金",
    "入金",
    "残高",
]
Hirogin_2page_List = [
    "日付",
    "摘要",
    "出金",
    "入金",
    "残高",
]
"相続_JA_1page_List" = [
    "起算日",
    "摘要",
    "貸借",
    "金額",
    "残高",
    "摘要2",
]
"相続_JA_2page_List" = [
    "日付",
    "摘要",
    "貸借",
    "金額",
    "残高",
    "摘要2",
]

[Setframe]
Nomal_DaySetList = [
    "1",
]
Nomal_MoneySet = [
    "3",
    "4",
    "5",
]
Nomal_ReplaceSet = [
    "2",
    "3",
    "4",
]
Hirogin_1page_DaySetList = [
    "1",
]
Hirogin_1page_MoneySet = [
    "3",
    "4",
    "5",
]
Hirogin_1page_ReplaceSet = [
    "2",
    "3",
    "4",
]
Hirogin_2page_DaySetList = [
    "1",
]
Hirogin_2page_MoneySet = [
    "3",
    "4",
    "5",
]
Hirogin_2page_ReplaceSet = [
    "2",
    "3",
    "4",
]
"相続_JA_1page_DaySetList" = [
    "1",
]
"相続_JA_1page_MoneySet" = [
    "4",
    "5",
]
"相続_JA_1page_ReplaceSet" = [
    "2",
    "6",
]
"相続_JA_2page_MoneySet" = [
    "4",
    "5",
]
"相続_JA_2page_ReplaceSet" = [
    "2",
    "6",
]

[LineSetting]
Nomal_Yoko = [
    [
        15,
        49,
        15,
        1479,
    ],
    [
        372,
        53,
        372,
        1479,
    ],
    [
        1570,
        57,
        1570,
        1479,
    ],
    [
        1947,
        63,
        1947,
        1479,
    ],
    [
        2627,
        61,
        2627,
        1479,
    ],
    [
        2935,
        59,
        2935,
        1479,
    ],
]
Nomal_Tate = [
    [
        15,
        47,
        3713,
        47,
    ],
    [
        10,
        107,
        3713,
        107,
    ],
    [
        18,
        210,
        3713,
        210,
    ],
    [
        24,
        274,
        3713,
        274,
    ],
    [
        1939,
        368,
        3713,
        368,
    ],
    [
        1954,
        430,
        3713,
        430,
    ],
    [
        1962,
        521,
        3713,
        521,
    ],
    [
        1946,
        594,
        3710,
        594,
    ],
    [
        1957,
        678,
        3713,
        678,
    ],
    [
        1958,
        756,
        3713,
        756,
    ],
    [
        1949,
        832,
        3713,
        832,
    ],
    [
        1955,
        913,
        3713,
        913,
    ],
    [
        1954,
        1006,
        3713,
        1006,
    ],
    [
        1952,
        1085,
        3713,
        1085,
    ],
    [
        1942,
        1154,
        3713,
        1154,
    ],
    [
        1955,
        1248,
        3713,
        1248,
    ],
    [
        1941,
        1337,
        3710,
        1337,
    ],
    [
        1947,
        1418,
        3713,
        1418,
    ],
]
Nomal_ReplaceStr = [
    "KDDI料金",
    "呉上下水道",
    "サンヨウガス",
    "カケコミ",
    "電話",
    "水道",
    "口座振替",
    "定期積金",
    "米",
    "新聞代",
]
Hirogin_1page_Yoko = [
    [
        10,
        14,
        10,
        3522,
    ],
    [
        497,
        19,
        497,
        3522,
    ],
    [
        971,
        23,
        971,
        3522,
    ],
    [
        1783,
        19,
        1783,
        3522,
    ],
    [
        2951,
        9,
        2951,
        3522,
    ],
]
Hirogin_1page_Tate = [
    [
        13,
        2,
        3549,
        2,
    ],
    [
        17,
        128,
        3549,
        128,
    ],
    [
        10,
        257,
        3549,
        257,
    ],
    [
        12,
        397,
        3549,
        397,
    ],
    [
        17,
        542,
        3549,
        542,
    ],
    [
        5,
        683,
        3549,
        683,
    ],
    [
        7,
        823,
        3549,
        823,
    ],
    [
        10,
        951,
        3549,
        951,
    ],
    [
        14,
        1085,
        3549,
        1085,
    ],
    [
        11,
        1214,
        3549,
        1214,
    ],
    [
        7,
        1353,
        3549,
        1353,
    ],
    [
        14,
        1504,
        3549,
        1504,
    ],
    [
        7,
        1632,
        3549,
        1632,
    ],
    [
        25,
        1888,
        3549,
        1888,
    ],
    [
        20,
        2024,
        3549,
        2024,
    ],
    [
        7,
        2179,
        3549,
        2179,
    ],
    [
        14,
        2301,
        3549,
        2301,
    ],
    [
        14,
        2447,
        3549,
        2447,
    ],
    [
        19,
        2583,
        3549,
        2583,
    ],
    [
        17,
        2705,
        3549,
        2705,
    ],
    [
        14,
        2836,
        3549,
        2836,
    ],
    [
        12,
        2969,
        3549,
        2969,
    ],
    [
        13,
        3112,
        3549,
        3112,
    ],
    [
        29,
        3235,
        3549,
        3235,
    ],
    [
        11,
        3391,
        3549,
        3391,
    ],
]
Hirogin_1page_ReplaceStr = [
    "トーケンコーポレーション",
    "TF）レクサス",
    "ニッポンセイサクキンユウコウコ",
    "マツモトトソウテン",
    "エイゼン",
    "ミツイマンテンドウ",
    "NSSダイドウセイメイ",
    "KDDIリヨウキン",
    "ホウジンETC　SMSF",
    "キョウドウネオンデン",
    "ジギョウフッカツシエンキン",
    "レッツ",
    "個人",
    "ミツハ",
    "マツシマ",
    "プラダ",
    "ショウコウカイギショヒロシマ",
    "トウキョウカイジョウニチドウ",
    "DFコモンリョウ",
    "チュピCOM",
    "ツカサケンチクコウボウ",
    "カ）ザザ",
]
Hirogin_2page_Yoko = [
    [
        6,
        5,
        6,
        1720,
    ],
    [
        244,
        8,
        244,
        1717,
    ],
    [
        475,
        14,
        475,
        1720,
    ],
    [
        873,
        8,
        873,
        1720,
    ],
    [
        1420,
        3,
        1420,
        1714,
    ],
]
Hirogin_2page_Tate = [
    [
        3,
        2,
        1722,
        2,
    ],
    [
        5,
        57,
        1722,
        57,
    ],
    [
        3,
        126,
        1722,
        126,
    ],
    [
        7,
        193,
        1722,
        193,
    ],
    [
        6,
        259,
        1722,
        259,
    ],
    [
        10,
        328,
        1722,
        328,
    ],
    [
        8,
        392,
        1722,
        392,
    ],
    [
        6,
        461,
        1722,
        461,
    ],
    [
        7,
        525,
        1722,
        525,
    ],
    [
        6,
        594,
        1722,
        594,
    ],
    [
        9,
        651,
        1722,
        651,
    ],
    [
        10,
        716,
        1722,
        716,
    ],
    [
        12,
        793,
        1722,
        793,
    ],
    [
        14,
        921,
        1722,
        921,
    ],
    [
        10,
        982,
        1722,
        982,
    ],
    [
        9,
        1041,
        1722,
        1041,
    ],
    [
        7,
        1115,
        1722,
        1115,
    ],
    [
        7,
        1183,
        1722,
        1183,
    ],
    [
        5,
        1245,
        1722,
        1245,
    ],
    [
        7,
        1305,
        1722,
        1305,
    ],
    [
        9,
        1367,
        1722,
        1367,
    ],
    [
        8,
        1436,
        1722,
        1436,
    ],
    [
        5,
        1514,
        1721,
        1514,
    ],
    [
        10,
        1579,
        1722,
        1579,
    ],
    [
        6,
        1653,
        1722,
        1653,
    ],
]
Hirogin_2page_ReplaceStr = [
    "トーケンコーポレーション",
    "TF）レクサス",
    "ニッポンセイサクキンユウコウコ",
    "マツモトトソウテン",
    "エイゼン",
    "ミツイマンテンドウ",
    "NSSダイドウセイメイ",
    "KDDIリヨウキン",
    "ホウジンETC　SMSF",
    "キョウドウネオンデン",
    "ジギョウフッカツシエンキン",
    "レッツ",
    "個人",
    "ミツハ",
    "マツシマ",
    "プラダ",
    "ショウコウカイギショヒロシマ",
    "トウキョウカイジョウニチドウ",
    "DFコモンリョウ",
    "チュピCOM",
    "ツカサケンチクコウボウ",
    "カ）ザザ",
]
"相続_JA_1page_Yoko" = [
    [
        15,
        49,
        15,
        1479,
    ],
    [
        372,
        53,
        372,
        1479,
    ],
    [
        1570,
        57,
        1570,
        1479,
    ],
    [
        1947,
        63,
        1947,
        1479,
    ],
    [
        2627,
        61,
        2627,
        1479,
    ],
    [
        2935,
        59,
        2935,
        1479,
    ],
]
"相続_JA_1page_Tate" = [
    [
        15,
        47,
        3713,
        47,
    ],
    [
        10,
        107,
        3713,
        107,
    ],
    [
        18,
        210,
        3713,
        210,
    ],
    [
        24,
        274,
        3713,
        274,
    ],
    [
        1939,
        368,
        3713,
        368,
    ],
    [
        1954,
        430,
        3713,
        430,
    ],
    [
        1962,
        521,
        3713,
        521,
    ],
    [
        1946,
        594,
        3710,
        594,
    ],
    [
        1957,
        678,
        3713,
        678,
    ],
    [
        1958,
        756,
        3713,
        756,
    ],
    [
        1949,
        832,
        3713,
        832,
    ],
    [
        1955,
        913,
        3713,
        913,
    ],
    [
        1954,
        1006,
        3713,
        1006,
    ],
    [
        1952,
        1085,
        3713,
        1085,
    ],
    [
        1942,
        1154,
        3713,
        1154,
    ],
    [
        1955,
        1248,
        3713,
        1248,
    ],
    [
        1941,
        1337,
        3710,
        1337,
    ],
    [
        1947,
        1418,
        3713,
        1418,
    ],
]
"相続_JA_1page_ReplaceStr" = [
    "KDDI料金",
    "呉上下水道",
    "サンヨウガス",
    "カケコミ",
    "電話",
    "水道",
    "口座振替",
    "定期積金",
    "米",
    "新聞代",
]
"相続_JA_2page_ReplaceStr" = [
    "KDDI料金",
    "呉上下水道",
    "サンヨウガス",
    "カケコミ",
    "電話",
    "水道",
    "口座振替",
    "定期積金",
    "米",
    "新聞代",
    "コウセイロウドウショウネンキン",
    "呉市後期保険料",
    "呉上下水道",
    "新厚生年金",
]
"相続_JA_2page_Yoko" = [
    [
        33,
        77,
        33,
        1518,
    ],
    [
        378,
        85,
        378,
        1518,
    ],
    [
        1579,
        91,
        1579,
        1518,
    ],
    [
        1968,
        111,
        1968,
        1518,
    ],
    [
        2642,
        103,
        2642,
        1518,
    ],
    [
        2934,
        103,
        2934,
        1518,
    ],
]
"相続_JA_2page_Tate" = [
    [
        33,
        85,
        3734,
        85,
    ],
    [
        1970,
        180,
        3734,
        180,
    ],
    [
        1968,
        255,
        3734,
        255,
    ],
    [
        1973,
        336,
        3734,
        336,
    ],
    [
        1981,
        395,
        3734,
        395,
    ],
    [
        1973,
        506,
        3734,
        506,
    ],
    [
        1970,
        571,
        3734,
        571,
    ],
    [
        1970,
        660,
        3734,
        660,
    ],
    [
        1963,
        729,
        3734,
        729,
    ],
    [
        1973,
        824,
        3734,
        824,
    ],
    [
        1965,
        891,
        3734,
        891,
    ],
    [
        1968,
        992,
        3734,
        992,
    ],
    [
        1975,
        1059,
        3734,
        1059,
    ],
    [
        1973,
        1160,
        3734,
        1160,
    ],
    [
        1963,
        1210,
        3734,
        1210,
    ],
    [
        1970,
        1322,
        3734,
        1322,
    ],
    [
        1965,
        1376,
        3734,
        1376,
    ],
    [
        1983,
        1484,
        3734,
        1484,
    ],
]
