[DataList]
#------------------------------------------------
Datas = ["JA","Hirogin","Momiji","HiroginSouzoku","JASouzoku","Tuka"]

[JA]
#------------------------------------------------
HidukeColNo = 1
MoneyCol = [4,5,6]
ChangeTextCol = [2]
ColumnName = ["日付","摘要","摘要2","出金","入金","残高"]
NyuName = "入金"
SyutuName = "出金"
ZanName = "残高"
ChangeText = [
    "ATM"
    ]

[Hirogin]
#------------------------------------------------
HidukeColNo = 1
MoneyCol = [3,4,5]
ColumnName = ["No","日付","預金番号1","預金番号2","摘要","出金","入金","残高"]

[Momiji]
#------------------------------------------------
HidukeColNo = 2
MoneyCol = [6,7,8]
ColumnName = ["No","日付","預金番号1","預金番号2","摘要","出金","入金","残高"]


[HiroginSouzoku]
#------------------------------------------------
HidukeColNo = 1
MoneyCol = [6,7,8]
ChangeTextCol = [4,9]
ColumnName = ["日付","No","無題","摘要","種類","出金","入金","残高","摘要2"]
NyuName = "入金"
SyutuName = "出金"
ZanName = "残高"
ChangeText = [
    "トヨタファイナンス(カブ",
    "ヒロシマギンコウDC",
    "オリコ",
    "ハートフォードセイメイホケ",
    "カゴメ",
    "イトウハム",
    "トウシンブンパイキン",
    "トウシンコウニュウ",
    "UC(アオヤマキャピタル)",
    "クレジット",
    "キュウヨ",
    "フリコミ",
    "リソク",
    "ハイトウキン",
    "フリカエ",
    "テイキ"
    ]


[JASouzoku]
#------------------------------------------------
HidukeColNo = 1
MoneyCol = [7,8]
ChangeTextCol = [6,9,10]
ColumnName = ["取引日","取引種別","取引区分","摘要","ネット情報","貸借","取引金額","残高","媒体区分","コメント"]
ChangeText = [
    "KDDI料金",
    "呉上下水道",
    "サンヨウガス",
    "#借",
    "通帳"
    ]

[Tuka]
#------------------------------------------------
HidukeColNo = 1
MoneyCol = [3,4,5]
ChangeTextCol = [1]
ColumnName = ["品名","数量","単価","金額","摘要"]
NyuName = "単価"
SyutuName = "金額"
ZanName = "摘要"
ChangeText = [
    "トヨタファイナンス(カブ",
    "ヒロシマギンコウDC",
    "オリコ",
    "ハートフォードセイメイホケ",
    "カゴメ",
    "イトウハム",
    "トウシンブンパイキン",
    "トウシンコウニュウ",
    "UC(アオヤマキャピタル)",
    "クレジット",
    "キュウヨ",
    "フリコミ",
    "リソク",
    "ハイトウキン",
    "フリカエ",
    "テイキ"
    ]